name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.CONFIG_METRICS_QUOKEQUACK }}
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
      - name: Default
        uses: lowlighter/metrics@latest
        with:
           filename: metrics.base.svg
           token: ${{ secrets.CONFIG_METRICS_QUOKEQUACK }}
           base: header, activity, community, repositories, metadata
      - name: MBTI Personality profile
        uses: lowlighter/metrics@latest
        with:
           filename: metrics.plugin.16personalities.svg
           token: ${{ secrets.CONFIG_METRICS_QUOKEQUACK }}
           base: ""
           plugin_16personalities: yes
           plugin_16personalities_url: https://www.16personalities.com/profiles/d6d91a8393310
           plugin_16personalities_sections: personality, traits, profile
           plugin_16personalities_scores: yes

      - name: Archievements
        uses: lowlighter/metrics@latest
        with:
           filename: metrics.plugin.achievements.compact.svg
           token: ${{ secrets.CONFIG_METRICS_QUOKEQUACK }}
           base: ""
           plugin_achievements: yes
           plugin_achievements_only: >-
                polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
                scripter, packager, explorer, infographile, manager
           plugin_achievements_display: compact
           plugin_achievements_threshold: X
      - name: Social Medias
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: medias.svg
          token: ${{ secrets.CONFIG_METRICS_QUOKEQUACK }}
          base: ""
          config_order: anilist
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_anilist: yes
          plugin_anilist_user: alaquoke
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 11
      - name: Fortune
        uses: lowlighter/metrics@latest
        with:
         filename: metrics.plugin.fortune.svg
         token: NOT_NEEDED
         base: ""
         plugin_fortune: yes
      - name: Half-year calendar
        uses: lowlighter/metrics@latest
        with:
           filename: metrics.plugin.isocalendar.svg
           token: ${{ secrets.CONFIG_METRICS_QUOKEQUACK}}
           base: ""
           plugin_isocalendar: yes
      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.CONFIG_METRICS_QUOKEQUACK }}
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: quokequack
          plugin_languages_colors: rainbow
      - name: Recently played games
        uses: lowlighter/metrics@latest
        with:
             filename: metrics.plugin.steam.svg
             token: NOT_NEEDED
             base: ""
             plugin_steam_token: ${{ secrets.TOKEN_STEAM }}
             plugin_steam: yes
             plugin_steam_user: "76561199447126221"
             plugin_steam_sections: recently-played
             plugin_steam_achievements_limit: 20





