name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.CONFIG_METRICS_QUOKEQUACK }}
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
      - name: Default
        uses: lowlighter/metrics@latest
        with:
           filename: metrics.base.svg
           token: ${{ secrets.CONFIG_METRICS_QUOKEQUACK }}
           base: header, activity, community, repositories, metadata
      - name: Archievements
        uses: lowlighter/metrics@latest
        with:
           filename: metrics.plugin.achievements.compact.svg
           token: ${{ secrets.CONFIG_METRICS_QUOKEQUACK }}
           base: ""
           plugin_achievements: yes
           plugin_achievements_only: >-
                polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
                scripter, packager, explorer, infographile, manager
           plugin_achievements_display: compact
           plugin_achievements_threshold: X
      - name: Social Medias
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: medias.svg
          token: ${{ secrets.CONFIG_METRICS_QUOKEQUACK }}
          base: ""
          config_order: anilist
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 5

